### ISSUE TITLE
specs

### ISSUE THREAD

**Issue by ionutcatalinsandu** [laravel-enso/products#1]
## Product Table (Root) (icon - product-hunt)
- [x]  manufacturer_id (nullable)
- [x]  measurement_unit_id
- [x]  name
- [x]  part_number
- [x]  internal_code (nullable)
- [x]  list_price (integer)
- [x]  vat_percent (nullable) (integer)
- [x]  package_quantity (nullable)
- [x]  description (nullable)
- [x]  is_active

## Pivot product_supplier
- [x] ids
- [x] is_default
- [x] acquisition_price (integer)

## Measurement Unit (Administration) (Icon - Ruler)
- [x] name
- [x] order_index
- [x] is_active
- [ ] seeder

- [x] tests

**Comment by aocneanu** [comment]
add docs
